server:
  port: 8080

spring:
  application:
    name: Demo

  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/DemoPOF
    username: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

